#!/bin/bash

FILENAME="$1"
BYTECODE=$2

if [ "$BYTECODE" == "bytecode" ]; then
    cd /MAIAN/tool; 
    for c in 0 1 2; do
        python3 maian.py -c "$c" -b "$FILENAME" 
    done
else
    export PATH="/data/bin:$PATH"
    chmod +x /data/bin/solc
    for CONTRACT in `python3 /data/bin/printContractNames.py "$FILENAME"`; do
            cd /MAIAN/tool; 
        for c in 0 1 2; do
            python3 maian.py -c "$c" -s "$FILENAME" "$CONTRACT"
        done
    done
fi
