VULNS_LOOKUP = {
    "Accepts_Ether": None,
    "Arithmetic_bugs": "Arithmetic Issues",
    "Callstack_Depth_Attack_Vulnerability": "Callstack Depth Attack Vulnerability",
    "Callstack_bug": "Arithmetic Issues",
    "CheckedCallStateUpdate": "Reentrancy",
    "Concurrency_bug": "Front-Running",
    "Delegatecall_to_user_supplied_address": "Delegate Call To Untrusted Contract",
    "Dependence_on_predictable_environment_variable": "Bad Randomness",
    "Dependence_on_tx_origin": "Access Control",
    "Destroyable": "Access Control",
    "Destructible": "Access Control",
    "Ether_leak": "Access Control",
    "Ether_lock": "Greedy",
    "Ether_lock_Ether_accepted_without_send": "Greedy",
    "Exception_State": "Assert Violations",
    "External_Call_To_User_Supplied_Address": "Reentrancy",
    "Integer_Arithmetic_Bugs": "Arithmetic Issues",
    "Integer_Overflow": "Arithmetic Issues",
    "Integer_Underflow": "Arithmetic Issues",
    "Jump_to_an_arbitrary_instruction": "Jump to an arbitrary instruction",
    "Modulo_bugs": "Arithmetic Issues",
    "Money_flow": None,
    "Multiple_Calls_in_a_Single_Transaction": "Denial of Service",
    "No_Ether_leak_no_send": None,
    "No_Ether_lock_Ether_refused": None,
    "Not_destructible_no_self_destruct": None,
    "OriginUsed": "Access Control",
    "OverflowLoopIterator": "Arithmetic Issues",
    "Overflow_bugs": "Arithmetic Issues",
    "Re_Entrancy_Vulnerability": "Reentrancy",
    "Reentrancy": "Reentrancy",
    "Reentrancy_bug": "Reentrancy",
    "ReentrantCall": "Reentrancy",
    "Signedness_bugs": "Arithmetic Issues",
    "State_access_after_external_call": "Reentrancy",
    "Time_Manipulation": "Time manipulation",
    "Timedependency_bug": "Front-Running",
    "Timestamp_Dependency": "Time manipulation",
    "Transaction_Ordering_Dependence": "Front-Running",
    "Transaction_Ordering_Dependence_TOD": "Front-Running",
    "Truncation_bugs": "Arithmetic Issues",
    "UnboundedMassOp": "Denial of Service",
    "UncheckedCall": "Unchecked Return Values For Low Level Calls",
    "Unchecked_Low_Level_Call": "Unchecked Return Values For Low Level Calls",
    "Unchecked_return_value_from_external_call": "Unchecked Return Values For Low Level Calls",
    "Underflow_bugs": "Arithmetic Issues",
    "Unprotected_Ether_Withdrawal": "Access Control",
    "Unprotected_Selfdestruct": "Access Control",
    "UnsecuredValueSend": "Access Control",
    "Write_to_an_arbitrary_storage_location": "Write to Arbitrary Storage Location"
}