docker_image:
  default: smartbugs/ethainter:latest
cmd_bytecode: ""
output_in_files:
  folder: "/home/reviewer/gigahorse-toolchain/logic/results.json"
output_parser: Ethainter
info: "Ethainter is a smart contract security analyzer for composite vulnerabilities. See the paper (Brent et al.: Ethainter: A Smart Contract Security Analyzer for Composite Vulnerabilities; In 41st ACM SIGPLAN Conference on Programming Language Design and Implementation, 2020)."
