docker_image:
  default: smartbugs/manticore:0.3.7
cmd: "{contract}"
cmd_bytecode: "{contract}"
output_in_files:
  folder: /results
output_parser: Manticore
info: Manticore is a symbolic execution tool for analysis of smart contracts and binaries.
