docker_image:
  default: smartbugs/teether:04adf56
cmd_bytecode: "{contract} 0x1234 0x1000 +1000"
output_parser: TeEther
info: teEther - Analysis and automatic exploitation framework for Ethereum smart contracts.
