docker_image:
  default: smartbugs/madmax:6e9a6e9
cmd_bytecode: ""
output_in_files:
  folder: "/MadMax/results.json"
output_parser: MadMax
info: Madmax consists of a series of analyses and queries that find gas-focussed vulnerabilities in Ethereum smart contracts.
