docker_image:
  default: smartbugs/maian:solc5.10
  solc<5: smartbugs/maian:solc4.25
cmd: /run_maian_solidity.sh
cmd_bytecode: /run_maian_bytecode.sh
output_parser: Maian
info: Maian is a tool for automatic detection of buggy Ethereum smart contracts of three different types prodigal, suicidal and greedy.
