docker_image:
  default: smartbugs/solhint
cmd: solhint -f unix -q
output_parser: Solhint
info: Open source project for linting solidity code. This project provide both security and style guide validations.
